export default {
    HOME: "/",
    ADMIN: "/admin",
    LOGIN: "/login",
    REGISTER: "/register",
    COURSES: "/courses",
    CART: "/cart",
    PAYMENT: "/payment",
    PROFILE: "/profile",
    ABOUT: "/about",
    GALLERY: "/gallery",
    BLOG: "/blog",
    CONTACT: "/contact",
    EVENT: "/event",
};
